-- STR SRC-DB SRC
-- STR OUT-DB OUT

-- OUT FOR ITSELF
insert into OUT.A select SRC.A where id > 0

-- ENV SRC-DB 'src_db'
INSERT IGNORE SYS_HOT_SEPARATION SELECT
    TABLE_NAME,0,NOW()
FROM
    INFORMATION_SCHEMA.TABLES
WHERE
    TABLE_SCHEMA = 'src_db';

-- ENV OUT-DB 'out_db'
-- OUT FOR ITSELF
INSERT IGNORE SYS_HOT_SEPARATION SELECT
    TABLE_NAME,0,NOW()
FROM
    INFORMATION_SCHEMA.TABLES
WHERE
    TABLE_SCHEMA = 'out_db';