DROP DATABASE IF EXISTS `prd_main`;
CREATE DATABASE `prd_main` DEFAULT CHARACTER SET utf8mb4;

DROP DATABASE IF EXISTS `prd_2018`;
CREATE DATABASE `prd_2018` DEFAULT CHARACTER SET utf8mb4;

DROP DATABASE IF EXISTS `dev_main`;
CREATE DATABASE `dev_main` DEFAULT CHARACTER SET utf8mb4;

DROP DATABASE IF EXISTS `lcl_main`;
CREATE DATABASE `lcl_main` DEFAULT CHARACTER SET utf8mb4;

