DROP DATABASE IF EXISTS `godbart_prd_main`;
CREATE DATABASE `godbart_prd_main` DEFAULT CHARACTER SET utf8mb4;

DROP DATABASE IF EXISTS `godbart_prd_2018`;
CREATE DATABASE `godbart_prd_2018` DEFAULT CHARACTER SET utf8mb4;

DROP DATABASE IF EXISTS `godbart_dev_main`;
CREATE DATABASE `godbart_dev_main` DEFAULT CHARACTER SET utf8mb4;

DROP DATABASE IF EXISTS `godbart_lcl_main`;
CREATE DATABASE `godbart_lcl_main` DEFAULT CHARACTER SET utf8mb4;

